---
title: "Using This Image"
author: M. Edward (Ed) Borasky
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Create a file named `.env` for your environment variables. This name appears in the top-level `.gitignore` file and thus will not be checked into Git!
2. In `.env`, define the environment variables:

    * `CONTAINER_JUPYTER_PORT`: the port you want the Jupyter notebook server to listen on in the container. The host port will be the same, so make sure it's not in use elsewhere.

    Example:
    
    ```
    CONTAINER_JUPYTER_PORT=8889
    ```
3. Type `docker-compose up`. Don't run this in the background; you'll need to copy an authentication key from the terminal.

    Docker-compose will create the network `jupyter_default`. Then it will build the `jupyter` image if it doesn't exist. Finally it will start the image in container `jupyter_jupyter_1`.
4. Testing / troubleshooting: If everything worked, you will see a link on the terminal. Copy that link and paste it into your browser and you should be in the notebook server in the `hacko` home directory. To stop the server, type `CTRL-C` in the terminal where you ran the `docker-compose up`.
5. What's in it?
This image is built on the Intel Python 3 Core image (<https://hub.docker.com/r/intelpython/intelpython3_core/>). To that I've added PostgreSQL client libraries, a non-root user `hacko`, and a Conda environment called `jupyter` for `hacko`.

I've just included `Jupyter`, `pandas` and `psycopg2` for now. You can install other packages from the notebook terminal via `conda` or `pip`.
