version: '3.4'
services:
  amazon:
    build:
      context: .
      dockerfile: Dockerfile.amazon
    image: amazon
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
