version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
      args:
        - DB_USERS_TO_CREATE
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
      - DB_USERS_TO_CREATE
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
  amazon:
    build:
      context: .
      dockerfile: Dockerfile.amazon
      args:
        - DB_USERS_TO_CREATE
    image: amazon
    environment:
      - DB_USERS_TO_CREATE
