FROM dpage/pgadmin4
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# add a non-privileged user
RUN useradd -s /bin/bash -U -m pgadmin
RUN chown -R pgadmin:pgadmin /home/pgadmin

# force TLS false
ENV PGADMIN_ENABLE_TLS=False
