version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
      args:
        - DB_USERS_TO_CREATE
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
      - DB_USERS_TO_CREATE
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: jupyter
    ports:
      - 8888:8888
