version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    image: pgadmin
    ports:
      - $HOST_PGADMIN_PORT:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: jupyter
    ports:
      - 8888:8888
