version: '3.4'
services:
  rstats:
    build:
      context: .
      dockerfile: Dockerfile.rstats
    image: rstats
    ports:
      - 8787:8787
    environment:
      - PASSWORD=$RSTUDIO_PASSWORD
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
      args:
        - DB_USERS_TO_CREATE
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
      - DB_USERS_TO_CREATE
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
