version: '3.4'
services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile.rstudio
    image: rstudio
    ports:
      - 8787:8787
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
      - DB_USERS_TO_CREATE
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
