version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
  pgadmin4:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin4
    image: pgadmin4
    ports:
      - $HOST_PGADMIN_PORT:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
