#! /bin/bash

# define parameters
export DBOWNER=transportation-systems
export PGDATABASE=transportation-systems-main

./1unpack-raw-data.bash
/usr/bin/time ./2create-stop-event-csvs.R
./3import-stop-event-csvs.bash
