#! /bin/bash

# define parameters
export DBOWNER=transportation-systems
export PGDATABASE=transportation-systems-main
export SCHEMA=tl_2017_41_tabblock10

echo "Creating schema '${SCHEMA}'"
psql -U ${DBOWNER} -d ${PGDATABASE} -c "CREATE SCHEMA ${SCHEMA};"

echo "Importing TriMet shapefiles"
pushd ~/Raw
export WHERE=https://www2.census.gov/geo/tiger/TIGER2017/TABBLOCK
for table in tl_2017_41_tabblock10
do
  echo "Downloading shapefile for ${table}"
  wget -nc -q $WHERE/${table}.zip
  rm -fr ${table}; mkdir $table; cd $table
  unzip -qq ../${table}.zip
  echo "Importing ${table}"
  ogr2ogr -f PostgreSQL -lco PRECISION=NO -nlt PROMOTE_TO_MULTI \
    -lco SCHEMA=${SCHEMA} PG:"dbname=${PGDATABASE}" ${table}.shp
  psql -U ${DBOWNER} -d ${PGDATABASE} -c "ALTER TABLE ${SCHEMA}.${table} OWNER TO \"${DBOWNER}\";"
  cd ..
done
popd

psql -U ${DBOWNER} -d ${PGDATABASE} -c "VACUUM ANALYZE;"
