version: '3.4'
services:
  pgadmin4:
    build:
      context: .
      dockerfile: Dockerfile
    image: pgadmin4
    ports:
      - $HOST_PGADMIN_PORT:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_ENABLE_TLS
