version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_POSTGRES_PORT
        - POSTGRES_PASSWORD
    image: postgis
    ports:
      - $HOST_POSTGRES_PORT:$CONTAINER_POSTGRES_PORT
