version: '3.4'
services:
    postgis-geocoder:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=$PGPASSWORD
            - PGDATA=/var/lib/postgresql/data/pgdata
        image: postgis-geocoder
        ports: 
        - '5438:5432'
        volumes:
        - /d/gisdata:/gisdata
        - /d/pgdata:/var/lib/postgresql/data/pgdata
