---
title: "Oregon OpenStreetMap Data"
author: "M. Edward (Ed) Borasky"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required resources
This example is a bit demanding. The core operation, creating a `pgRouting` database of the TriMet service area, requires a bit over 4 GB of RAM to run. As a result, it won't run on my 8 GB laptop in Docker, which only has 2 GB of RAM available. It should run with any Docker host big enough to allocate 5 GB of RAM to the `postgis` container. It only requires the `postgis` container.

## Running the scripts
1. Get a Docker host with enough RAM to run it.
2. Bring up the `postgis` service with `docker-compose`.
3. Log in to the container as `postgres`.
4. Run the `download-data.bash` script. It will
    * Download the TriMet boundary shapefile and convert it to GeoJSON.
    * Extract the bounding box from the GeoJSON.
    * Download the most recent OpenStreetMap dataset for Oregon. This appears to be the smallest dataset that covers the Portland metro area.
    * Create a dataset with just the data inside the bounding box.
5. Run the `make-routing-database.bash` script. As noted above, this requires over 4 GB of RAM. The script will
    * Create a database `osm_routing`.
    * Create the `postgis`, `pgrouting` and `hstore` extensions in the database.
    * Create and populate three schemas, one for each mode: cars, bicycles and pedestrians. This is the part that takes some time - about 15 minutes for each mode on my workstation. I believe the three modes can be run concurrently but I have not tested it.
    * Create a `pg_dump` backup of the database. The backup is currently about 736 megabytes.

## References
* Obe, Regina, and Hsu, Leo (2017) _pgRouting: A Practical Guide_, Locate Press, ISBN  978-0989421737, <https://locatepress.com/pgrouting>
* TriMet Developer Resources - Geospatial Data: <https://developer.trimet.org/gis/>
* OpenStreetMap data download for Oregon: <http://download.geofabrik.de/north-america/us/oregon.html>
* osmconvert: <https://wiki.openstreetmap.org/wiki/Osmconvert>
* osm2pgrouting: <https://github.com/pgRouting/osm2pgrouting>
