#! /bin/bash

# define parameters
export DBOWNER=transportation-systems
export PGDATABASE=transportation-systems-main

echo "Importing Safety_Hotline_Tickets.csv"
psql -U ${DBOWNER} -d ${PGDATABASE} -f "scrubbed.psql"
