---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sp)
library(sf)
library(tmap)
library(lubridate)

```

# create the census block polygon lookup tables
```{r}
or_census_block_polygons <- read_sf("~/Raw/tl_2017_41_tabblock10/tl_2017_41_tabblock10.shp")
wa_census_block_polygons <- read_sf("~/Raw/tl_2017_53_tabblock10/tl_2017_53_tabblock10.shp")
or_census_block_polygons <- or_census_block_polygons %>% 
  st_transform("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
wa_census_block_polygons <- wa_census_block_polygons %>% 
  st_transform("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
or_census_block_polygons <- or_census_block_polygons %>% 
  select(census_block = GEOID10, geom_polygon_4326 = geometry)
wa_census_block_polygons <- wa_census_block_polygons %>% 
  select(census_block = GEOID10, geom_polygon_4326 = geometry)

```

# read the passenger census
```{r}
passenger_census <- read_csv(
  "~/Raw/passenger_census.csv",
  col_types = cols(
    DIRECTION = col_integer(),
    LOCATION_ID = col_integer(),
    OFFS = col_integer(),
    ONS = col_integer(),
    PUBLIC_LOCATION_DESCRIPTION = col_character(),
    ROUTE_NUMBER = col_integer(),
    SERVICE_KEY = col_character(),
    STOP_SEQ = col_integer(),
    SUMMARY_BEGIN_DATE = col_date(format = "%d-%b-%y"),
    X_COORD = col_double(),
    Y_COORD = col_double()
  )
)
colnames(passenger_census) <- tolower(colnames(passenger_census))
passenger_census$service_key <- trimws(passenger_census$service_key)

```

# create the point geometry column
```{r}
passenger_census <- SpatialPointsDataFrame(
  coords = select(passenger_census, x_coord, y_coord),
  data = passenger_census,
  proj4string = CRS("+init=epsg:2913")
)
passenger_census <- spTransform(passenger_census, CRS("+init=epsg:4326")) %>%
  as("sf") %>%
  select(summary_begin_date:y_coord, geom_4326 = geometry)

```

# add the census block and year columns
```{r}
passenger_census <- passenger_census %>% st_join(or_census_block_polygons)
passenger_census <- passenger_census %>% mutate(year = year(summary_begin_date))
brief_passenger_census <- passenger_census %>% filter(year == 2009 | year == 2017)
```

# summarize by census block and year
```{r}
annual_census_block_ridership <- passenger_census %>% 
  mutate(year = year(summary_begin_date)) %>% 
  group_by(census_block, year)
gc()
annual_census_block_ridership <- annual_census_block_ridership %>% 
  summarize(total_ons = sum(ons), stops = n())
gc()
annual_census_block_ridership <- annual_census_block_ridership %>% 
  arrange(desc(total_ons)) %>% 
  ungroup()
gc()

```

```{r}
tmap_mode("view")
qtm(
  annual_census_block_ridership %>% filter(year == 2009) %>% as("Spatial"), 
  fill = "total_ons"
)
qtm(
  annual_census_block_ridership %>% filter(year == 2017) %>% as("Spatial"), 
  fill = "total_ons"
)
```

