#! /bin/bash

# define parameters
export DBOWNER=transportation-systems
export PGDATABASE=transportation-systems-main
export HERE=${PWD}

echo "Downloading BikeTown dataset"
pushd ~/Raw
wget -nc https://s3.amazonaws.com/biketown-tripdata-public/BiketownPublicTripData201804.zip
unzip -o BiketownPublicTripData201804.zip
echo "Stacking CSV files"
cp ${HERE}/header biketown.csv
grep -h -v RouteID PublicTripData/*.csv >> biketown.csv
popd

echo "Cleaning BikeTown data"
./clean.R
echo "Importing BikeTown data"
psql -U ${DBOWNER} -d ${PGDATABASE} -f "biketown.psql"
